/************************************************
 *  infoBox.java
 *  Author: Jim Drewes, 2002
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 *
 * Displays a simple "Okay" dialog box.
 ************************************************/

public class infoBox extends java.awt.Dialog {

    /** Creates new form infoBox */
    public infoBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);  // Its a modal box.. you can't use the other forms while it is open.
        initComponents();
    }

    public infoBox(java.awt.Frame parent, boolean modal, String text, String title) {
        super(parent, modal);  // initailize the box...
        initComponents();
        this.setTitle(title);  // Set the title...
        jLabel1.setText(text);  // Set the text.
        this.pack();
        this.setLocation(100, 100);
    }

// Forte Generated Code.
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
private void initComponents() {//GEN-BEGIN:initComponents
jLabel1 = new javax.swing.JLabel();
jButton1 = new javax.swing.JButton();

setLocationRelativeTo(getOwner());
addWindowListener(new java.awt.event.WindowAdapter() {
public void windowClosing(java.awt.event.WindowEvent evt) {
closeDialog(evt);
}
});

jLabel1.setText("No Message");
add(jLabel1, java.awt.BorderLayout.CENTER);

jButton1.setText("Okay");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

add(jButton1, java.awt.BorderLayout.SOUTH);

pack();
}//GEN-END:initComponents
// End Forte Generated Code.

// If they click "Okay"
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    setVisible(false);  // Remove this dialog box.
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JLabel jLabel1;
private javax.swing.JButton jButton1;
// End of variables declaration//GEN-END:variables

}
