#!/bin/sh
# @(#)UNINSTALL-jai	16.1 03/07/16
# usage: UNINSTALL-jai

echo "Uninstalling Java Advanced Imaging"

rm -f *jai.txt
rm -f lib/jai_core.jar
rm -f lib/jai_codec.jar
rm -f lib/mlibwrapper_jai.jar
rm -f lib/libmlib_jai.so
if [ \( `uname` = "SunOS" \) -a \( `uname -p` = "sparc" \) ]; then
    rm -f lib/cpu/sparcv9+vis/libmlib_jai.so
    rm -f lib/cpu/sparcv9+vis2/libmlib_jai.so
    rmdir lib/cpu/sparcv9+vis
    rmdir lib/cpu/sparcv9+vis2
    rmdir lib/cpu
fi
rmdir lib
rm -f UNINSTALL-jai

echo "Done"
